config_map:
  - name: SPRINT_API_SERVICE_URI
    value: http://wiremock-docker.{{ project }}.svc:8080/sprint-board/sprint-api
  - name: STORY_API_SERVICE_URI
    value: http://wiremock-docker.{{ project }}.svc:8080/sprint-board/story-api
  - name: TASK_API_SERVICE_URI
    value: http://wiremock-docker.{{ project }}.svc:8080/sprint-board/task-api
  - name: JAEGER_SERVICE_NAME
    value: build-{{ microservice.name }}
  - name: JAEGER_SAMPLER_TYPE
    value: const
  - name: JAEGER_SAMPLER_PARAM
    value: 1
  - name: JAEGER_SAMPLER_MANAGER_HOST_PORT
    value: jaeger-agent.{{ product.name }}-monitoring.svc:5778    
  - name: JAEGER_AGENT_HOST
    value: jaeger-agent.{{ product.name }}-monitoring.svc      