apiVersion: v1
kind: Service
metadata:
  labels:
    app: sprint-api
  name: sprint-api
  namespace: prod
spec:
  ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    - name: 8778-tcp
      port: 8778
      protocol: TCP
      targetPort: 8778
  selector:
    app: sprint-api
    deploymentconfig: sprint-api
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
